version: '3.4'

#  docker-compose exec server bash
#  docker-compose run --rm server bash
#  docker-compose up
#  docker-compose stop
#  docker-compose ps

# env localhost-server

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    ports:
      - "5434:5432"
    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./initTables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3001:3000"
    command: ["npm", "start"]

  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["node", "./server.js"]
